### PR TITLE
make jdtls work

### PR DESCRIPTION
**Pull request by Alexis12119**
make sure you installed jdtls through mason.nvim

### CODE REVIEW

**Comment by JonEasy** [comment]
Seems that the client is attaching but still no autocompletion. 
image

See below logs:
image

**Comment by Alexis12119** [comment]
maybe try to wait 30 secs or 1 minute. Because jdtls completion is really taking time to autocompletes

**Comment by JonEasy** [comment]
I enables the detailed logs and got: 
image
And 
image

**Comment by Alexis12119** [comment]
If it's alright with you can you try my config? Just to make sure that there are no other problems?

Link: https://github.com/Alexis12119/nvim-config

**Comment by JonEasy** [comment]
Sure. Will give it a try and will let you know in half day

**Comment by Alexis12119** [comment]
**NOTE:** When the `jdtls` is attached, make sure to count 5-10 seconds before typing anything.

**Comment by JonEasy** [comment]
I cloned your repo and got the same error:  
image
Btw nice configuration!

**Comment by Alexis12119** [comment]
Thanks, based on the logs  we only have one difference and it's `Command _java.reloadBundles.command is no supported on client`

But, is it not working even on simple java code?

**Comment by JonEasy** [comment]
I do not see any autocompletion nor syntax highlighting....

**Comment by Alexis12119** [comment]
maybe there's something wrong with `on_attach` and `capabilites`.

**Comment by Alexis12119** [comment]
is nvim-jdtls still installed in your system?

**Comment by Alexis12119** [comment]
if yes, you just need to edit the `java.lua` in ftplugin folder and not on lspconfig.

**Comment by Alexis12119** [comment]
what's the value of `on_attach` and `capabilites`?

**Comment by Alexis12119** [comment]
I wonder what's the problem.

**Comment by JonEasy** [comment]
I am using the java.lua from ftplugin and disabling the one from lspconfig. 
How can I see the value of both?

**Comment by Alexis12119** [comment]
what do you mean both?

**Comment by JonEasy** [comment]
Using your approach (ftplugin/java.lua) The client is though attached to the server... 
image

**Comment by JonEasy** [comment]
These"on_attach and capabilites"

**Comment by Alexis12119** [comment]
you can see it in your setup
I mean this 
https://github.com/Alexis12119/nvim-config/blob/master/ftplugin/java.lua#L60-L61

**Comment by Alexis12119** [comment]
because if there are mistake on the path of `on_attach` and `capabilities` it will result to this

Screenshot (1319)

**Comment by Alexis12119** [comment]
I'm confused because here in my setup it's working, but when you tried it's not working.

Screenshot (1321)

**Comment by JonEasy** [comment]
Did you try my config using ftplugin/java.lua ?  If my capabilities and on_attach work for you  then must be some other error from the system and not config.

**Comment by Alexis12119** [comment]
I haven't tried it because my internet is slow right now and when configuring `nvim-jdts`, you only need to add `java.lua` in ftplugin folder. But on the pull request i used the path that should work for your config i mean [this](https://github.com/JonEasy/nvim/pull/1/files#diff-5af8102c567bf6f4d78de421cb38681de588f1f8665c424e3663417982197074R60-R61) .

Did you try to reinstall `jdtls` using `mason.nvim`?

If even in simple java code, it's not working that's the problem for config, but if it's not then there's another reason.

**Comment by Alexis12119** [comment]
maybe I'll try your config to find out if it's working

**Comment by Alexis12119** [comment]
Trying out your config may take a while because you have many plugins to install.

**Comment by JonEasy** [comment]
Sure let me know. I could create a new branch and try you config from scratch and it worked fine. If you have any idea on how to inspect the values of my capabilities ( can not print it) let me know.

**Comment by Alexis12119** [comment]
you haven't setup the other plugins?

**Comment by Alexis12119** [comment]
It's working on my machine

Screenshot (1322)

**Comment by Alexis12119** [comment]
I'm currently using the fork

**Comment by Alexis12119** [comment]
maybe I'll also push some changes I made

**Comment by JonEasy** [comment]
Let me check

**Comment by Alexis12119** [comment]
Oh, I haven't push the changes I made yet

**Comment by JonEasy** [comment]
OK I wait until I see new changes.

**Comment by Alexis12119** [comment]
You can check it now.

**Comment by JonEasy** [comment]
When is your last commit? I only see two from more than 10 hours ago. You pushed it ?

**Comment by Alexis12119** [comment]
I'm confused why it's not push.

**Comment by Alexis12119** [comment]
wait, haha

**Comment by Alexis12119** [comment]
when I clone my fork, I only see readme and nothing more

**Comment by Alexis12119** [comment]
Did you see my new changes now?

**Review by JonEasy — APPROVED** [review]

**Comment by JonEasy** [comment]
image

**Comment by Alexis12119** [comment]
Is lspsaga installed on your machine?

**Comment by Alexis12119** [comment]
Also I forgot to add this in the `init.lua`, because I deleted them accidentally.
```
let g:python_host_prog ='/home/jonel/anaconda3/envs/py38/bin/python'
let g:python3_host_prog = '/home/jonel/anaconda3/envs/py38/bin/python'
```

**Comment by Alexis12119** [comment]
try reinstalling lspsaga because there's breaking changes on lspsaga and I fixed them.

**Comment by Alexis12119** [comment]
Try reinstalling/updating lspsaga because there's breaking changes on the latest commit of lspsaga and I fixed it.

**Comment by JonEasy** [comment]
Lspsaga is installed. Are we importing the reuire("jpv") correctly ?

**Comment by JonEasy** [comment]
When opening nvim :
image

**Comment by JonEasy** [comment]
Will be back in few hours.

Missatge de Alexis Corporal ***@***.***> del dia ds., 21 de
gen. 2023 a les 15:26:

**Comment by JonEasy** [comment]
REinstalled and lspsaga disappeared but  when opening java file 
image

**Comment by Alexis12119** [comment]
what is your neovim version?

**Comment by JonEasy** [comment]
v0.9.0-dev

**Comment by Alexis12119** [comment]
oh, my I made a mistake on java.lua

**Comment by Alexis12119** [comment]
I added () on `on_attach`

**Comment by Alexis12119** [comment]
change this https://github.com/JonEasy/nvim/blob/master/ftplugin/java.lua#L61

**Comment by Alexis12119** [comment]
into `on_attach = require("jpv.lsp.handlers").on_attach,`

**Comment by Alexis12119** [comment]
Is there stil any errors?

I tried it again and It's working fine

Screenshot (1324)

**Comment by JonEasy** [comment]
Will be right back after some hours and will check again! Btw if you add
some comments to your code I might pull it for use. But would like to
hnderstand what it is doing, for color scheme, appearance on telewcope etc
And thanks a lot!!!

**Comment by Alexis12119** [comment]
You're welcome, I hope it's working now.

**Comment by Alexis12119** [comment]
maybe when you get back, I'm already sleeping so try cloning my forked repo because I pushed my fixes on some issues I made.

**Comment by JonEasy** [comment]
I removed the () on attach and having no initial erros but 
image

**Comment by Alexis12119** [comment]
Looks like you're using it for work, maybe it needs more specific and complex configuration

**Comment by JonEasy** [comment]
You mean that something is wrong with my settings? I am using Ubuntu on WSL.

**Comment by Alexis12119** [comment]
no, it requires more configuration

**Comment by Alexis12119** [comment]
like here in chirs configuration

https://github.com/ChristianChiarulli/nvim/blob/master/ftplugin/java.lua

**Comment by JonEasy** [comment]
Well I have a working setup for js, typescript, python. But my end goal is
to have it fully functioning for java and kotlin ( with debugging options)

**Comment by JonEasy** [comment]
I will have a look, but this one is starting to get complex

**Comment by Alexis12119** [comment]
try looking at these lines first.

https://github.com/ChristianChiarulli/nvim/blob/master/ftplugin/java.lua#L157-L167

**Comment by Alexis12119** [comment]
In simple java code, is it working?

**Comment by JonEasy** [comment]
I even added the lines from chris ( see the code on my repo) and not
getting any diagnostic nor completion

Missatge de Alexis Corporal ***@***.***> del dia ds., 21 de
gen. 2023 a les 22:36:

**Comment by Alexis12119** [comment]
In simple java code like this, is the diagnostics and completions working?
```java
public class filename {
    public static void main(String[] args) {
    }
}
```

**Comment by Alexis12119** [comment]
looks like there's nothing wrong on your latest commit, but I wonder how to solve this problem we have right now.

**Comment by JonEasy** [comment]
I opened a new file with it and it worked. It seems that my shortcuts for
go to next diagnostic error is not working. Which key map are you using for
displaying errors then ?

Missatge de Alexis Corporal ***@***.***> del dia ds., 21 de
gen. 2023 a les 22:53:

**Comment by Alexis12119** [comment]
The errors are automatically showing up to me, here's my [keymap](https://github.com/Alexis12119/nvim-config/blob/master/lua/plugins/which-key.lua#L161-L167l) but I'm currently using other plugin for that, but that should also work in other ways.

**Comment by JonEasy** [comment]
So when opening a legacy java file with spring framework code seems not
really working though...

Missatge de Jonel Palou ***@***.***> del dia ds., 21 de gen.
2023 a les 23:02:

**Comment by Alexis12119** [comment]
I'll try researching on how to make it work.

**Comment by JonEasy** [comment]
Now completion and diagnostics seem to work but not the keymaps. I press ]d ( next diagnostic error) 
image

**Comment by JonEasy** [comment]
Thanks. you want to video connect and allocate a specific time next week ?

Missatge de Alexis Corporal ***@***.***> del dia ds., 21 de
gen. 2023 a les 23:10:

**Comment by Alexis12119** [comment]
Are you busy right now? maybe if yes maybe I'll try next week. Are we gonna use google meet?

**Comment by JonEasy** [comment]
We can do it now indeed! Send me an invite and will join the call.

Missatge de Alexis Corporal ***@***.***> del dia ds., 21 de
gen. 2023 a les 23:18:

**Comment by Alexis12119** [comment]
Ok, sorry but my camera currently broken but don't worry my mic is working.

Here's the link:
https://meet.google.com/crz-cucq-mju

**Comment by Alexis12119** [comment]
I'm in the call now.

**Comment by Alexis12119** [comment]
jdtls is not working on my machine because it's exiting immediately.

**Comment by Alexis12119** [comment]
Your config is not working on my laptop now.

**Comment by JonEasy** [comment]
What is the error ?

Missatge de Alexis Corporal ***@***.***> del dia ds., 21 de
gen. 2023 a les 23:51:

> Your config is not working on my laptop now.
>

**Comment by Alexis12119** [comment]
`Client 1 quit with exit code 1 and signal 0`

**Comment by Alexis12119** [comment]
I tried researching about spring framework with neovim, but I can't find anything that will help.

**Comment by Alexis12119** [comment]
I see one 
https://www.reddit.com/r/neovim/comments/w2ygmg/using_neovim_to_work_with_spring_boot/

But spring boot

**Comment by Alexis12119** [comment]
Sorry, but It looks like I can't be any help to you to solve your problem. I hope you find a solution soon. Maybe try asking in the neovim community on how to make it work.

sorry again :(

**Comment by JonEasy** [comment]
Thanks a lot!!!

Missatge de Alexis Corporal ***@***.***> del dia dg., 22 de
gen. 2023 a les 0:03:

**Pull request merged**
